layout_spectrum: 0.1084383
typography_spectrum: 0.01089761
color:
  saturation: 0.5052668
  lightness: 0.6420612
  brandStrength: 0.6077425
  brandColors:
    - '#F1F0EE'
    - '#890B77'
    - '#278780'
    - '#E1B5D7'
    - '#9AC4BD'
  rhythmicContrast: 0.3113229
name: SocialNutrition
